website/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

import officehours.views as views
import website.settings as settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('<str:course_offering_slug>/requests/today', views.requests_today, name='requests-today'),
    path('<str:course_offering_slug>/requests/all', views.requests_all, name='requests-all'),
    path('<str:course_offering_slug>/requests/<int:request_id>', views.request_detail, name='request-detail'),
    path('<str:course_offering_slug>/my-request', views.my_request, name='my-request'),
    path('<str:course_offering_slug>/status', views.status, name='status'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},
    name='logout')
]

webapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Quarter(models.Model):
    ais_num = models.PositiveIntegerField(primary_key=True)
    year = models.PositiveIntegerField()
    quarter = models.CharField(max_length=3, choices = [("aut", "Autumn"),
                                                        ("win", "Winter"),
                                                        ("spr", "Spring"),
                                                        ("sum", "Summer")])

    class Meta:
        unique_together = (("year", "quarter"),)

    def __str__(self):
        return "{} {}".format(self.get_quarter_display(), self.year)

    @property
    def academic_year(self):
        if self.quarter in ("sum", "aut"):
            return "{}/{:02d}".format(self.year, (self.year % 100) + 1)
        elif self.quarter in ("win", "spr"):
            return "{}/{:02d}".format(self.year - 1, (self.year % 100))


class Course(models.Model):
    ais_num = models.PositiveIntegerField(primary_key=True)
    subject = models.CharField(max_length=4)
    catalog_code = models.IntegerField(validators=[MinValueValidator(10000),
                                                   MaxValueValidator(99999)])
    name = models.CharField(max_length=256)

    def __str__(self):
        return "{} {} - {} ({})".format(self.subject, self.catalog_code, self.name, self.ais_num)


class CourseOffering(models.Model):
    STATE_OPEN = 10
    STATE_CLOSED = 20

    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    quarter = models.ForeignKey(Quarter, on_delete=models.CASCADE)
    archived = models.BooleanField(default=False)
    state = models.PositiveIntegerField(choices = [(STATE_OPEN,   "Open"),
                                                   (STATE_CLOSED, "Closed")],
                                        default = STATE_CLOSED)

    url_slug = models.CharField(max_length=256, unique=True)

    servers = models.ManyToManyField(User, blank=True)

    class Meta:
        unique_together = (("course", "quarter"),)

    def __str__(self):
        return "{} {} - {} ({})".format(self.subject, self.catalog_code, self.name, self.quarter)

    @property
    def ais_num(self):
        return self.course.ais_num

    @property
    def subject(self):
        return self.course.subject

    @property
    def catalog_code(self):
        return self.course.catalog_code

    @property
    def name(self):
        return self.course.name

    def get_active_request(self, user):
        reqs = self.request_set.filter(students = user, state__in = Request.ACTIVE_STATES)

        assert len(reqs) <= 1

        if len(reqs) == 0:
            return None
        else:
            return reqs[0]


class Slot(models.Model):
    course_offering = models.ForeignKey(CourseOffering, on_delete=models.CASCADE)

    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    room = models.CharField(max_length=64)

    def __str__(self):
        return "{} ({})".format(self.date, self.interval)

    @property
    def interval(self):
        start = self.start_time.strftime("%I:%M %p")
        end = self.end_time.strftime("%I:%M %p")
        return "{} - {}".format(start, end)

class Request(models.Model):
    STATE_PENDING = 10
    STATE_SCHEDULED = 20
    STATE_INPROGRESS = 30
    STATE_COMPLETED = 40
    STATE_NOSHOW = 50
    STATE_COULDNOTSEE = 60
    STATE_CANCELLED = 70
    STATE_INVALID = 80

    ACTIVE_STATES = (STATE_PENDING, STATE_SCHEDULED, STATE_INPROGRESS)

    TYPE_REGULAR = 10
    TYPE_EXPRESS = 20

    course_offering = models.ForeignKey(CourseOffering, on_delete=models.CASCADE)
    students = models.ManyToManyField(User, related_name="requests")
    server = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="assigned_requests")
    date = models.DateField()

    slots = models.ManyToManyField(Slot)
    actual_slot = models.ForeignKey(Slot, on_delete=models.CASCADE, blank=True, null=True, related_name="assigned_slot")

    service_start_time = models.TimeField(blank=True, null=True)
    service_end_time = models.TimeField(blank=True, null=True)

    state = models.PositiveIntegerField(choices = [(STATE_PENDING,     "Pending"),
                                                   (STATE_SCHEDULED,   "Scheduled"),
                                                   (STATE_INPROGRESS,  "In Progress"),
                                                   (STATE_COMPLETED,   "Completed"),
                                                   (STATE_NOSHOW,      "No-show"),
                                                   (STATE_COULDNOTSEE, "Could not schedule"),
                                                   (STATE_CANCELLED,   "Cancelled"),
                                                   (STATE_INVALID,     "Invalid"),
                                                   ],
                                        default = STATE_PENDING)

    type = models.PositiveIntegerField(choices = [(TYPE_REGULAR, "Regular"),
                                                  (TYPE_EXPRESS, "Express")
                                                 ],
                                        default = TYPE_REGULAR)

    description = models.TextField()

    @property
    def is_active(self):
        return self.state in Request.ACTIVE_STATES

    def get_state_class(self):
        if self.state in (Request.STATE_PENDING,):
            return "btn-warning"
        elif self.state in (Request.STATE_SCHEDULED, Request.STATE_INPROGRESS):
            return "btn-success"
        elif self.state in (Request.COMPLETED,):
            return "btn-info"
        elif self.state in (Request.STATE_NOSHOW, Request.STATE_COULDNOTSEE, Request.STATE_CANCELLED, Request.STATE_INVALID):
            return "btn-danger"
        else:
            return "btn-info"

templates/uchicago-cs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{# Load the tag library #}
{% load bootstrap4 %}
{% load static %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<link rel="stylesheet" type="text/css" href="{% static 'uchicago-cs/style.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

{% block extra_head %}{% endblock %}

<meta name="viewport" content="width=device-width, initial-scale=1">

    <title>CS 121 Office Hours</title>
</head>

<body>



<nav class="navbar navbar-expand-sm navbar-dark bg-faded">
  <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'index' %}">CS 121 Office Hours</a>
      </div>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="collapsibleNavbar">

    <ul class="nav navbar-nav mr-auto">
        {% if user.is_authenticated %}

      {% if user_is_server %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'requests-today' course_offering.url_slug %}">Today's Requests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'requests-all' course_offering.url_slug %}">All Requests</a>
      </li>

      {% endif %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'status' course_offering.url_slug %}">Status</a>
      </li>


        {% endif %}
    </ul>

    <ul class="nav navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">

          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="fas fa-user"></span> {{ user }}
              {% if user.is_impersonate %} <br/>(Impersonating) {% endif %}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if user.student %}
              <a class="dropdown-item" href="{% url 'profile' %}">My profile</a>
          {% endif %}
            <div class="dropdown-divider"></div>
            {% if user.is_impersonate %}
                <a class="dropdown-item" href="{% url 'impersonate-stop' %}">Stop impersonating</a>
            {% endif %}
            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
        <span class="glyphicon glyphicon-user"></span>
        <a class="nav-link" href="{% url 'social:begin' 'google-oauth2' %}">Login</a>
      </li>
        {% endif %}
    </ul>

  </div>
  </div>

</nav>

{# Display django.contrib.messages as Bootstrap alerts #}


<div class="container">
{% bootstrap_messages %}
<br/>
        {% block content %}{% endblock %}
</div>

</body>
</html>

templates/uchicago-cs/index.html
{% extends "uchicago-cs/base.html" %}
{% load bootstrap4 %}
{% load mathfilters %}

{% block extra_head %}

{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <p>
    <p>Logged in as {{ user.username }}</p>
    </p>


{% else %}
    <p>
    Welcome!
    </p>

{% endif %}
{% endblock %}

templates/uchicago-cs/my-request.html
{% extends "uchicago-cs/base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block extra_head %}
{{ form.media }}
<script src="{% static 'uchicago-cs/request-form.js' %}"></script>

<script>
$(document).ready(function(){
    $('#cancel').click(function(){
        $('#cancelform').submit();
    });
    console.log("Hello!")
    setup_zoom_input();
    console.log("Hello 2!")
});
</script>
{% endblock %}


{% block content %}

{% if active_req %}

    <div class="modal fade" id="confirm-cancel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5>Are you sure?</h5>
                </div>
                <div class="modal-body">

                    <p>
                        If you are sure you want to do this, click on "Cancel my request".
                        Otherwise, press "Go Back" to close this window.
                    </p>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Go Back</button>
                    <a href="#" id="cancel" class="btn btn-danger danger">Cancel my request</a>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
     <div class="card-body">
        <h4 class="card-title">Request for {{ active_req.date }}</h4>

          <p>
              <button type="button" class ="{{active_req.get_state_class}}" disabled>{{active_req.get_state_display}}</button>
          </p>

     {% if active_req.is_pending %}
          <p>
              You requested the following times:
          </p>

         <ul>
             {% for slot in active_req.slots.all %}
                 <li>{{ slot }}</li>
             {% endfor %}
         </ul>
     {% endif %}

     {% if active_req.is_scheduled or active_req.is_inprogress %}
          <p>
              You have been scheduled for <b>{{ active_req.actual_slot.interval }}</b>.<br/>

              {% if active_req.is_scheduled_online %}
                  <p>
                      Zoom URL: <a href="{{ active_req.zoom_url }}" target="_blank">{{ active_req.zoom_url }}</a>
                  </p>
              {% else %}
                  Please go to <em>{{ active_req.actual_slot.room }}</em> at that time.
              {% endif %}
          </p>

     {% endif %}

               <p>Request description:</p>
      <div class="form-group">
    <textarea class="form-control" rows="3" readonly>{{ active_req.description }}</textarea>
  </div>


{% if active_req.is_pending or active_req.is_scheduled %}
         <form action="{%url 'request-detail' active_req.course_offering.url_slug active_req.pk %}" id="cancelform" method="post" class="form">
         {% csrf_token %}
         <input type="hidden" name="update-type" id="update-type" value="cancel"/>
         <input type="hidden" name="next-page" id="next-page" value="{% url 'my-request' active_req.course_offering.url_slug %}"/>
         {% buttons %}
         {% if active_req.is_pending %}
         <a href="{% url 'request-detail' active_req.course_offering.url_slug active_req.pk %}" class="btn btn-primary" role="button">Edit your request</a>
         {% endif %}
         <input type="button" value="Cancel Request" id="cancelBtn" data-toggle="modal" data-target="#confirm-cancel" class="btn btn-danger" />
         {% endbuttons %}
         </form>
{% endif %}

     </div>
    </div>

{% else %}
    {% if form %}

    <h4>Request for {{ date }}</h4>


       <form action="{{ form_action }}" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">
          {{ button_label }}
        </button>
      {% endbuttons %}
       </form>

    {% else %}
        <p>There are no slots available on this date</p>
    {% endif %}
{% endif %}

{% endblock %}

templates/uchicago-cs/request.html
{% extends "uchicago-cs/base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block extra_head %}
{{ form.media }}
    <script src="{% static 'uchicago-cs/request-form.js' %}"></script>

    <script>
        $(document).ready(function(){
            setup_zoom_input();
        });
    </script>
{% endblock %}


{% block content %}


    <h4>Request for {{ req.date }}</h4>

       <form action="{{ form_action }}" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">
          {{ button_label }}
        </button>
      {% endbuttons %}
       </form>

{% endblock %}

templates/uchicago-cs/requests-all.html
{% extends "uchicago-cs/base.html" %}
{% load bootstrap4 %}
{% load render_table from django_tables2 %}

{% block content %}

    <h2>Requests</h2>

    {% render_table table_all %}


{% endblock %}

templates/uchicago-cs/requests-tab.html
{% load bootstrap4 %}

<div class="modal fade" id="confirm-action-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5>Are you sure?</h5>
            </div>

            <div class="modal-body" id="confirm-msg">

            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Go Back</button>
                <a href="#" id="confirm-action-btn" class="btn btn-danger danger">Yes, do it</a>
            </div>
        </div>
    </div>
</div>


{% if tab_active %}
  <div id="{{tab_id}}" class="tab-pane fade show active">
{% else %}
  <div id="{{tab_id}}" class="tab-pane fade">
{% endif %}
  <div id="accordion">
    {% for req in requests %}
  <div class="card">
    <div class="card-header" id="{{tab_id}}-{{req.pk}}-heading">
      <h5 class="mb-0">
        <button class="btn btn-link{% if expand_request == req.pk %} collapsed{% endif %}" data-toggle="collapse" data-target="#{{tab_id}}-{{ req.pk }}-collapse" aria-expanded="true" aria-controls="collapseOne">
         {{req.get_accordion_display}}
        </button>
      </h5>
    </div>

    <div id="{{tab_id}}-{{ req.pk }}-collapse" class="collapse{% if expand_request == req.pk %} show{% endif %}" aria-labelledby="{{tab_id}}-{{req.pk}}-heading" data-parent="#accordion">
      <div class="card-body">
                <p>
              <button type="button" class ="{{req.get_state_class}}" disabled>{{req.get_state_display}}</button>
          </p>

      {% if req.is_pending %}
          <h4>Slots:</h4>
          <ul>
             {% for slot in req.ordered_slots %}
                 <li>{{ slot }}</li>
             {% endfor %}
         </ul>
     {% endif %}

          <p>
              <b>E-mail</b>: <a href="mailto:{{ req.student.email }}">{{ req.student.email }}</a>
          </p>

     {% if req.is_scheduled or req.is_inprogress %}
          <p>
             Scheduled for <b>{{ req.actual_slot.interval }}</b>.
          </p>
         {% if req.is_scheduled %}
         <p>
             Scheduled by <b>{{ req.server.get_full_name }}</b> (<a href="mailto:{{ req.server.email }}">{{ req.server.email }}</a>)
         </p>
         {% elif req.is_inprogress %}
         <p>
             Assigned to <b>{{ req.server.get_full_name }}</b> (<a href="mailto:{{ req.server.email }}">{{ req.server.email }}</a>)
         </p>
         {% endif %}

          {% if req.is_scheduled_online %}
          <p>
              Zoom URL:

              {% if req.is_scheduled %}
                  <a href="{{ req.zoom_url }}" target="_blank" onclick="return confirm('You have not claimed this request. Are you sure you want to open this Zoom link?')">{{ req.zoom_url }}</a>
              {% elif req.is_inprogress %}
                  <a href="{{ req.zoom_url }}" target="_blank">{{ req.zoom_url }}</a>
              {% endif %}

          </p>
          {% endif %}


     {% endif %}

          <h4>Description:</h4>
      <div class="form-group">
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" readonly>{{ req.description }}</textarea>
  </div>



  <div class="row">
    <!-- LEFT FORM -->
    <div class="col-sm text-left">

        {% if req.is_pending %}
             <form action="{% url 'request-detail' req.course_offering.url_slug req.pk %}" id="scheduleform_{{ req.pk }}" method="post" class="form-inline">
             {% csrf_token %}
             <input type="hidden" name="update-type" value="schedule"/>
             <input type="hidden" name="next-page" id="schedule-next-page_{{ req.pk }}" value="{% url 'requests-today' course_offering.url_slug %}"/>
             <input type="hidden" name="next-hash" id="schedule-next-hash_{{ req.pk }}" value="scheduled"/>

             <select name="slot" class="form-control">
                 {% for slot in req.ordered_slots %}
                     <option value="{{slot.pk}}">{{ slot }}</option>
                 {% endfor %}
             </select>
             {% buttons %}
             <button type="submit" class="btn btn-primary">
            Schedule
            </button>
             {% endbuttons %}
             </form>
        {% elif req.is_scheduled %}
            <form action="{% url 'request-detail' req.course_offering.url_slug req.pk %}" id="claimform_{{ req.pk }}" method="post" class="form-inline">
                {% csrf_token %}
                    <input type="hidden" name="update-type" value="start-service"/>
                    <input type="hidden" name="next-page" id="claim-next-page_{{ req.pk }}" value="{% url 'requests-today' course_offering.url_slug %}"/>
                    <input type="hidden" name="next-hash" id="claim-next-hash_{{ req.pk }}" value="in-progress"/>
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Claim this request</button>
                {% endbuttons %}
            </form>
        {% elif req.is_inprogress %}
            <form action="{% url 'request-detail' req.course_offering.url_slug req.pk %}" id="doneform_{{ req.pk }}" method="post" class="form-inline">
                {% csrf_token %}
                    <input type="hidden" name="update-type" value="complete-service"/>
                    <input type="hidden" name="next-page" id="done-next-page_{{ req.pk }}" value="{% url 'requests-today' course_offering.url_slug %}"/>
                    <input type="hidden" name="next-hash" id="done-next-hash_{{ req.pk }}" value="completed"/>
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Mark as Done</button>
                {% endbuttons %}
            </form>
        {% endif %}
    </div>
    <div class="col-sm text-right">
        <!-- RIGHT FORM -->
        {% if req.is_pending or req.is_scheduled or req.is_inprogress %}
        <form action="{% url 'request-detail' req.course_offering.url_slug req.pk %}" id="actionform_{{ req.pk }}" method="post" class="form-inline float-sm-right">
            {% csrf_token %}
            <input type="hidden" name="confirm" id="action-confirm_{{ req.pk }}"/>
            <input type="hidden" name="next-page" id="action-next-page_{{ req.pk }}" value="{% url 'requests-today' course_offering.url_slug %}"/>
            {% if req.is_scheduled %}
            <input type="hidden" name="next-hash" id="action-next-page_{{ req.pk }}" value="scheduled"/>
            {% elif req.is_inprogress %}
            <input type="hidden" name="next-hash" id="action-next-page_{{ req.pk }}" value="in-progress"/>
            {% endif %}

            <select name="update-type" id="update-type_{{ req.pk }}" class="form-control">
                <option selected disabled value="none">-- Select an action --</option>
                <optgroup label="Mark as...">
                    {% if not req.is_pending %}
                    <option value="complete-service">Done</option>
                    <option value="no-show">No Show</option>
                    {% endif %}
                    <option value="could-not-see">Could Not Be Seen</option>
                </optgroup>
                {% if not req.is_pending %}
                <optgroup label="Send notification...">
                    <option value="running-late">Running late to Zoom meeting</option>
                    <option value="invalid-zoom-link">Zoom link does not work</option>
                    <option value="not-in-zoom">Not in Zoom meeting</option>
                </optgroup>
                {% endif %}
            </select>
            {% buttons %}
                <input type="button" value="Apply" data-id="{{ req.pk }}" data-target="#confirm-action" class="btn btn-success applyBtn" />
            {% endbuttons %}
        </form>
        {% endif %}
    </div>
  </div>
  </div>
    </div>
  </div>
    {% endfor %}
  </div>
  </div>

templates/uchicago-cs/requests-today.html
{% extends "uchicago-cs/base.html" %}
{% load bootstrap4 %}

{% block extra_head %}
<script>
confirmation_msgs = {
    "no-show":
        `<p>You are going to mark this request as a no-show.</p>
         <p>Note: the student does not receive any e-mail notification, but the request will no longer appear as pending or active on their end.
            They will be able to make a new request.</p>
         <p>Are you sure?</p>`,
    "complete-service":
        `<p>You are going to mark this request as done.</p>
         <p>Note: the student does not receive any e-mail notification, but the request will no longer appear as pending or active on their end.
            They will be able to make a new request.</p>
         <p>Are you sure?</p>`,
    "could-not-see":
        `<p>You are going to mark this request as a request we were unable to get to. The student will receive an e-mail notification about this,
            and will be informed that their next request will be prioritized.</p>
         <p>Are you sure?</p>`,
    "running-late":
        `<p>You are going to send an e-mail notification to the student to let them know you are running late. You will be CC'd on the e-mail,
            and the student may reply to this e-mail.</p>
         <p>Are you sure?</p>`,
    "invalid-zoom-link":
        `<p>You are going to send an e-mail notification to the student to let them know that their Zoom link doesn't work. You will be CC'd on the e-mail,
            and the student may reply to this e-mail.</p>
         <p>Are you sure?</p>`,
    "not-in-zoom":
        `<p>You are going to send an e-mail notification to the student to let them know you tried to access their Zoom meeting, but they were either not
            there or they did not let you in from the waiting room. You will be CC'd on the e-mail,
            and the student may reply to this e-mail.</p>
         <p>Are you sure?</p>`,

}

    $(document).on("click", ".applyBtn", function() {
        var req_pk = $(this).data('id');
        var actionform = '#actionform_' + req_pk;
        var updateselect = '#update-type_' + req_pk;
        var update_type = $(updateselect).val();

        if (update_type == null) {
            window.alert("Please pick an action!");
            return;
        }

        if (!(update_type in confirmation_msgs)) {
            window.alert("Unsupported action.");
            return;
        }

        $('#confirm-msg').html(confirmation_msgs[update_type]);

        $('#confirm-action-btn').click(function(){
            $(actionform + ' #confirm').val("yes");
            $(actionform).submit();
        });

        $('#confirm-action-modal').modal("show");
    });
</script>
{% endblock %}

{% block content %}

    <h2>Today's Requests</h2>

<ul class="nav nav-tabs" id="todayTabs">
  <li class="nav-item active"><a class="nav-link" data-toggle="tab" href="#soon">Pending Soon ({{  requests_pending_soon|length }})</a></li>
  <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#today">Pending Today ({{  requests_pending_today|length }})</a></li>
  <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#scheduled">Scheduled ({{  requests_scheduled|length }})</a></li>
  <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#in-progress">In Progress ({{  requests_inprogress.count }})</a></li>
  <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#completed">Completed ({{  requests_completed.count }})</a></li>
</ul>

<div class="tab-content">

{% include "./requests-tab.html" with requests=requests_pending_soon tab_id="soon" tab_active=True %}

{% include "./requests-tab.html" with requests=requests_pending_today tab_id="today" %}

{% include "./requests-tab.html" with requests=requests_scheduled tab_id="scheduled" %}

{% include "./requests-tab.html" with requests=requests_inprogress tab_id="in-progress" %}

{% include "./requests-tab.html" with requests=requests_completed tab_id="completed" %}

</div>


    <script>
$('#todayTabs a').click(function(e) {
  e.preventDefault();
  $(this).tab('show');
});

// store the currently selected tab in the hash value
$("ul.nav-tabs > li > a").on("shown.bs.tab", function(e) {
  var id = $(e.target).attr("href").substr(1);
  window.location.hash = id;
});

// on load of the page: switch to the currently selected tab
var hash = window.location.hash;
$('#todayTabs a[href="' + hash + '"]').tab('show')
</script>

{% endblock %}

templates/uchicago-cs/status.html
{% extends "uchicago-cs/base.html" %}
{% load bootstrap4 %}

{% block extra_head %}
{{ form.media }}

{% endblock %}


{% block content %}


    <h4>Office Hours Status ({{ date }})</h4>

{% if not slot_requests %}

There are no office hours on this date.

{% else %}

    <p>There are currently <strong>{{ total_pending }}</strong> pending requests for office hours.</p>

    <div class="alert alert-secondary" role="alert">
        <strong>Note</strong>: The "# Requests" column represents the number of pending requests that included
        that time slot in the request. It does not represent the number of students who are waiting to be seen
        at exactly that time, so you should treat it as an indirect measure of how busy a given time slot
        might be.
    </div>


    <table class="table">
  <thead>
    <tr>
      <th scope="col">Slot</th>
      <th scope="col"># Requests</th>
      <th scope="col">Scheduled</th>
      <th scope="col">In Progress</th>
      <th scope="col">Completed</th>
    </tr>
  </thead>
  <tbody>
    {% for slot, counts in slot_requests.items %}
        <tr>
            <th scope="row">{{ slot.interval }}
                {% if slot.online %}[Online]{% endif %}
            </th>
          <td>{{counts.num_requests}}</td>
          <td>{{counts.scheduled}}</td>
          <td>{{counts.inprogress}}</td>
          <td>{{counts.completed}}</td>
        </tr>
    {% endfor %}
  </tbody>
</table>


{% endif %}


{% endblock %}